version: "3"
services:
  nginx:
    build:
        context: .
        dockerfile: nginx/Dockerfile
    ports:
        - "8080:80"
    networks:
        - "internal"
    volumes:
      - ./:/var/www/html/
      - ./nginx:/var/log/nginx/
    container_name: rest_nginx
networks:
  internal:
    driver: bridge
